### ISSUE TITLE
Aoe Loot en raid (à confirmé)

### ISSUE THREAD

**Issue by GeneralissimeDarklinks** [Athissa/Tracker#11]
**Describe the issue you're having**: lorsque on tue un groupe de mob les loot sont censé ce regroupé or en raid cela n'as pas été le cas on retrouve le même problème de loot si on fouille pas lebon cadavre (déja ramassé x/x)

**Explain how you expect it work**: en théorie si on résume lorsque le dernier monstre du groupe est tué il regroupe tout les loots des monstres prêt de lui

**Steps to reproduce the problem**:

1. aller dans un raid (exemple la bataille du mont Hyjal)
2. faire apparaitres les premières vague et tuer un groupe de monstre
3. essayer de loot les cadavres

**Comment by AGrygor** [comment]
L'exemple du mont Hyjal l'explique, le raid loot est bug dans cette instance en particulier. Peut-être aussi dans d'autres instances. Mais majoritairement le loot aoe fonctionne correctement. Sujet clot.
