### ISSUE TITLE
Enhancement Shaman / Spell / Maelstrom Weapon

### ISSUE THREAD

**Issue by MagvinCZ** [Athissa/Tracker#112]
Doesn´t give any maelstrom - no procs
http://www.wowhead.com/spell=187880/maelstrom-weapon

**Comment by AVyrax** [comment]
It's not supposed to proc, is it giving you the correct amount of maelstrom?

**Comment by MagvinCZ** [comment]
Sorry, my bad, I wrote it badly... It just doesn't give any maelstrom
