### ISSUE TITLE
Frozen Soul

### ISSUE THREAD

**Issue by FroYoGuy** [Athissa/Tracker#12]
**Describe the issue you're having**: So, there might be a bug that causes this artifact trait to deal a f-ton of damage for no reason at all.

**Explain how you expect it work**: Should deal much less damage

**Steps to reproduce the problem**:

1. Engage a hostile enemy (preferably another player so you can see the recap)
2. Use "Remorseless Winter" with the artifact trait "Frozen Soul" active on the "Blades of the Fallen prince" and wait for it to end.
3. Ask the other player to send screenshots of the recap, it should show ridiculous numbers (over 5M in my case)

**Links to Wowhead, YouTube, etc**: I don't know how long this link lasts: http://tinypic.com/r/2hhpu1x/9

**Comment by Athissa** [comment]
Fixed
