### ISSUE TITLE
Mage skill barrer bug arcane

### ISSUE THREAD

**Issue by Zael98** [Athissa/Tracker#125]
**Describe the issue you're having**: when i use the  barrer of arcane mage dont absorb nothing 0p

**Explain how you expect it work**: the shield should absorb any dmg

**Steps to reproduce the problem**:

1. I put the shield
2. he put a shield on my life
3. he dissapear pass 1m or destroy the shield

**Links to Wowhead, YouTube, etc**: http://es.wowhead.com/spell=235450/barrera-prismatica

**Comment by Athissa** [comment]
Spell Fixed
Thank you for your report
