### ISSUE TITLE
[Quest] Highmountain - This guy in the Costume

### ISSUE THREAD

**Issue by Turokn** [Athissa/Tracker#13]
**Issue :** Can't choose to talk to her.

**How it should work :** When interacting with Tamara Sigmund, the player should have the choice to use the flypath or talk to her.

**Steps to reproduce the problem** : 

1. Get the quest
2. Try to talk to her

Quest : http://www.wowhead.com/quest=40244/that-guy-in-the-costume
NPC : http://www.wowhead.com/npc=94973/tamara-sigmund

**Comment by Athissa** [comment]
fixed
