### ISSUE TITLE
Starsurge dont work

### ISSUE THREAD

**Issue by Zael98** [Athissa/Tracker#139]
**Describe the issue you're having**: in the druid starsurge dont work sometimes

**Explain how you expect it work**: when u use this skill the skill should be jump the skill

**Steps to reproduce the problem**:

1. Use the skill
2. jump the skill
3. cooldown

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=78674/starsurge

**Comment by A-Edina** [comment]
The issue is not Starsurge it is Astral Power build up on a previous combat registration that is not kept. Ergo, its reset to zero (it shouldn't) but your astral power bar still shows you have AP.
