### ISSUE TITLE
starfall druid

### ISSUE THREAD

**Issue by Zael98** [Athissa/Tracker#140]
**Describe the issue you're having**: cant jump the skill

**Explain how you expect it work**: when u press the skill, the skill should be jump

**Steps to reproduce the problem**:

1. jump the skill
2. skill was be jump
3. cooldown

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=191034/starfall

**Comment by A-Edina** [comment]
The issue is not starfall, it is Astral Power build up on a previous combat registration that is not kept. Ergo, its reset to zero (it shouldn't) but your astral power bar still shows you have AP.
