### ISSUE TITLE
Rogue/Subtlety/Honor Talent/Thief's Bargain 

### ISSUE THREAD

**Issue by Sozeone** [Athissa/Tracker#145]
**Describe the issue you're having**:
Thief's Bargain doesn't work at all.....
**Explain how you expect it work**:
http://www.wowhead.com/spell=212081/thiefs-bargain
**Steps to reproduce the problem**:

1. http://www.wowhead.com/spell=212081/thiefs-bargain
2. Look at health pool/do some dmg while stealthed/ cast Vanish and look at its cooldown
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by bewilder1** [comment]
I don't know with damage but the health reduction is working.
