### ISSUE TITLE
Systeme de Loot Legion

### ISSUE THREAD

**Issue by GeneralissimeDarklinks** [Athissa/Tracker#186]
**Describe the issue you're having**: à l'heure actuel en donjon on gagne un objet pour 5 personne ou alors 25 personne ce qui est abusif pour les Ninjas

**Explain how you expect it work**: normalement on gagne Un objet par personne cela as été fais ainsi.

**Steps to reproduce the problem**
1. Aller en donjon/World Boss
2. Tué ce dernier.
3. Constater les loots

**Links to Wowhead, YouTube, etc**:
http://www.millenium.org/wow/legion/actualites/legion-systeme-de-loot-butin-maitre-personnel-groupe-legendaire-rng-breloque-145412

**Comment by AGrygor** [comment]
Pour l'instant vu le nombre de personnes dans la communaute, le systeme sera tel qu'il est jusqu'a ce que Athissa en decide autrement. Je lock ce sujet. Bon Jeu.

**Comment by amaries** [comment]
Il est plus complexe de se stuff directement en donjon sans le butin personnel. Cela s'ajoute à des procs de donjon aléatoire pas forcement constant.
