### ISSUE TITLE
Monster don't attack and just regen 

### ISSUE THREAD

**Issue by Wyzerty** [Athissa/Tracker#188]
**Describe the issue you're having**:
All the red monsters that I attack just don't move or run in all direction and just regen their life.
**Explain how you expect it work**:
The monster should attack normaly 
**Steps to reproduce the problem**:

1. attack monster
2. watch them 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by AGrygor** [comment]
This bug was fixed, if you used this character before the fix, delete it and make a new one. Otherwise, contact a gm on discord. Issue closed.
