### ISSUE TITLE
Raid Instance Bug (Raid Instance Not able to be finished)

### ISSUE THREAD

**Issue by RagingRevenge50** [Athissa/Tracker#192]
**Describe the issue you're having**:
One of the bosses is no where to be found and does not spawn
**Explain how you expect it work**:
I expect the boss to actually appear when he is supposed to. He Is supposed to be located the one of the elites
**Steps to reproduce the problem**:

1. Join Raid Instance

2. Kill 2 of the 3 bosses

3. Find the one thats bugged/Is nowhere to be found

**Links to Wowhead, YouTube, etc**:

**Comment by AGrygor** [comment]
No wowhead links, videos or even screenshots. Even the raid is not mentioned. Sorry but I am closing this issue.
