### ISSUE TITLE
[Dungeon] [Entrance] Vault of the Warderns

### ISSUE THREAD

**Issue by Varriesa** [Athissa/Tracker#193]
**Describe the issue you're having**:
Azsuna is spawned well, but somewhere some mobs are missing. I was curious about dungeon Vault of the Warderns, so I went there to check if it's works. Unfortunately no. This dungeon is "closed", and isn't there a portal to enter to this dungeon.
**Explain how you expect it work**:
http://www.wowhead.com/vault-of-the-wardens
https://youtu.be/Ft0_Tz52VgY?t=1m26s
**Steps to reproduce the problem**:
1. try to enter this dungeon

**Screenshot**:
http://imgur.com/a/5HX89
On the ss you can see there portal is missing.

**Comment by AGrygor** [comment]
This dungeon is still not implemented. Hopefully soon. Good day!
