### ISSUE TITLE
[Priest] Divinity

### ISSUE THREAD

**Issue by Reetsu** [Athissa/Tracker#211]
**Describe the issue you're having**: The Priest talent "Divinity" is proccing with every healing spell.

**Explain how you expect it work**: Divinity should activate only when an Holy Word is cast.

**Steps to reproduce the problem**:

1. Cast any healing spell
2. Divinity is now active, granting the Priest a bonus 15% on healing done almost permanently

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=197031/divinity

**Comment by Athissa** [comment]
Fixed
