### ISSUE TITLE
traveler's tundra mammoth Alliance version

### ISSUE THREAD

**Issue by assassin14** [Athissa/Tracker#215]
The two vendors Gnimo and Hakmud of Argus is missing from the Vendor mount
very annoying when your farming out in broken isle for AP when you get trash from packs of mobs 

The mount should have the 2 NPC's on it

1.Use the mount as alliance 
2. summons the mount with no NPC's on it
3. 

http://www.wowhead.com/item=44235/reins-of-the-travelers-tundra-mammoth
http://www.wowhead.com/npc=32639/gnimo
http://www.wowhead.com/npc=32638/hakmud-of-argus

**Comment by APharaoh** [comment]
I tried it and its working! try to delete your cache and try again maybe its just a visual bug.
