### ISSUE TITLE
Rend and Tear Guardian druid

### ISSUE THREAD

**Issue by assassin14** [Athissa/Tracker#221]
i am not sure if this is working at all, i cannot tell if the damage reduction or damage increase is working at the moment

While in Bear Form, Thrash also increases your damage dealt to the target, and reduces your damage taken from the target by 2% per application of Thrash.

http://www.wowhead.com/spell=204053/rend-and-tear

**Comment by Ygdrassill** [comment]
#408 yes it is  a bug whit the talent
