### ISSUE TITLE
Retribution Paladin

### ISSUE THREAD

**Issue by Shiftt927** [Athissa/Tracker#224]
**Describe the issue you're having**: 
Blade of Wrath- Proc appears but cooldown is not reseted so I can't use my proc.
Divine Hammer- It doesn't generates holy power.
Also one more thing, Judgement is hitting 2 targets and it doesn't generate holy power but I'm not sure if its a bug or it should works like that.

**Comment by AGrygor** [comment]
Hello dear player, first I must insist that you respect the issue format. Secondly, it is supposed to be one issue per bug, not one in all. So I'm going to have to close this issue. Thank you.
