### ISSUE TITLE
Bug Draenor Blacksmithing Recipe

### ISSUE THREAD

**Issue by pekacmarko** [Athissa/Tracker#232]
**Describe the issue you're having**: I bought the recipe and learned, and nothing happened.
Recipe must teach me: Smoldering Breastplate, Smoldering Greaves, Smoldering Helm, Truesteel Ingot,
Secrets of Draenor Blacksmithing.  

**Explain how you expect it work**: Recipe must teach me these things.
**Steps to reproduce the problem**:

1. 
2. 
3. 
Please Fix !!!  :)

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/item=115356/draenor-blacksmithing#teaches-spell

**Comment by Athissa** [comment]
fixed

**Comment by pekacmarko** [comment]
recipe still not work.
