### ISSUE TITLE
Barrière Flamboyante Mage Feu

### ISSUE THREAD

**Issue by GeneralissimeDarklinks** [Athissa/Tracker#240]
**Describe the issue you're having**: le sort n'absorbe pas de dégats

**Explain how you expect it work**: le sort est censé Infliger des dégats en plus d'en Absorber

**Steps to reproduce the problem**:

1. Affronté un monstre
2. Lancer Barrière Flamboyante
3. constater le manque d'absorption

**Links to Wowhead, YouTube, etc**:  http://fr.wowhead.com/spell=235313

**Comment by Athissa** [comment]
Spell fixed
Thank you for your repport
