### ISSUE TITLE
Starsurge / Balance Druid

### ISSUE THREAD

**Issue by Erylion** [Athissa/Tracker#263]
**Describe the issue you're having**: If I want to cast starsurge at 40 or more astral power nothing happens. I can't cast it. 

**Explain how you expect it work**: If I have at least 40 astral power I should can cast starsurge.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by AGrygor** [comment]
Issue #139
