### ISSUE TITLE
Artifact weapon The Silver Hand missing off hand 

### ISSUE THREAD

**Issue by Shime89** [Athissa/Tracker#304]
**Describe the issue you're having**: Holy paladin missing off hand Tome of the Silver Hand.
book is part of weapon. Or there should not have off hand.

**Explain how you expect it work**: When you take a weapon must have in off hand tome of silver hand.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:  http://www.wowhead.com/item=128824/tome-of-the-silver-hand
http://www.wowhead.com/artifact-calc/paladin/holy/AkYjIwA
![dwd](https://cloud.githubusercontent.com/assets/28353417/25958606/5b9dc902-3671-11e7-9d03-c350b4b07380.png)

**Comment by AGrygor** [comment]
Hello it's just a visual bug, the stats are taken into consideration. I will close this issue. Good day and good game on Athissa.
