### ISSUE TITLE
I can not heal my friends

### ISSUE THREAD

**Issue by Jakeiswin** [Athissa/Tracker#329]
When i try to heal my friends his says "You can not do this to a jcj target as long as the jcj is disabled"

I thought it would work

heal a friend

https://images.discordapp.net/.eJwtyEsOhCAMANC7cADKTyXehgBBo7aE1rgwc_eZxWze4r3qHqda1SbSeQUoO2caRbPQSK3qRtTOmvrOOtMFSSTl7aooDN56Y2Zn3GKsDzEu07_mEH9OwXrr4MYD6UHdsanPFwHoIrU.9RzQXXBHEf3NqAruA9usD5oZmd4?width=896&height=560

**Comment by VictorTyne** [comment]
This is not a bug.

The error message gives you all the information you need. If your PvP flag is disabled, you cannot heal a player whose PvP flag is enabled.
