### ISSUE TITLE
Frost Mage Spell (Ice Lance)

### ISSUE THREAD

**Issue by MohamedXIII** [Athissa/Tracker#344]
**Describe the issue you're having**: The spell doesn't deal triple damage against frozen targets.

**Explain how you expect it work**: Ice Lance damage is triple against frozen targets.

**Steps to reproduce the problem**:

1. Cast Ice Lance against a frozen target.
2. The damage is triple the normal damage of Ice Lance.

**Links to Wowhead, YouTube, etc**: http://www.wowdb.com/spells/30455-ice-lance

**Comment by Athissa** [comment]
Spell Fixed
Thank you for your report
