### ISSUE TITLE
Val'sharah Lytheron Gloomscale eggs near Bradensbrook

### ISSUE THREAD

**Issue by Drazlok** [Athissa/Tracker#349]
**Describe the issue you're having**:
I was trying to break the eggs of those hydra looking creatures Lytheron Gloomscales and they actually move and attack me back. 
**Explain how you expect it work**:
Honestly, i expected that NOT to work... Its kinda funny at the very beginning but then it gets annoying when you are actually getting murdered by a bunch of eggs
**Steps to reproduce the problem**:

1. Deal any amount of damage to the egg without breaking it
2. Watch it killing you.

**Links to Wowhead, YouTube, etc**:

**Comment by AVyrax** [comment]
This is actually the most effective way to level to 110 if you were unaware.

**Comment by AGrygor** [comment]
Like GM Vyrax said, this is one the most effective you to level to 110. When you level up a bit more, the attack of the eggs won't be much of a problem. I am closing this issue. Good day and good game on Athissa.
