### ISSUE TITLE
barrière prismatique

### ISSUE THREAD

**Issue by aizen2012** [Athissa/Tracker#351]
**Describe the issue you're having**:protection absente

**Explain how you expect it work**:barrière prismatique est un bouclier qui est censer absorbe des dégâts réduire les dégât magique reçus de 15% et  réduire la durée des effet magique néfaste de 25 % sauf que la il n y a rien ni protection ni réduction le sort visuel est la mais les dégâts son directes  

**Steps to reproduce the problem**:

1. lancer barrière prismatique

**Links to Wowhead, YouTube, etc**: http://fr.wowhead.com/spell=235450/barriere-prismatique

**Comment by Athissa** [comment]
Spell fixed
Thank you for your repport
