### ISSUE TITLE
[NPC] Highmountain - Marakhan

### ISSUE THREAD

**Issue by Turokn** [Athissa/Tracker#38]
**Issue**: The NPC Marakhan which you have to kill for completing the quest "Rite of Blood" auto-attacks are too powerful.

**How it should work**: Marakhan should do a lot less damage with his auto-attacks.

**Steps to reproduce the problem**:

1. Get the quest "Rite of Blood"
2. Progress normally through it.
3. Fight Marakhan

Rite of Blood : http://www.wowhead.com/quest=39860/rite-of-blood
Marakhan : http://www.wowhead.com/npc=97418/marakhan

**Comment by Athissa** [comment]
fixed
