### ISSUE TITLE
Cone of Cold

### ISSUE THREAD

**Issue by RamzGlory** [Athissa/Tracker#385]
**Describe the issue you're having**:
When i use (Cone of Cold) on a target they don't get slowed they only take the dmg it says they are gonna take but nothing else happens.

**Explain how you expect it work**:
When you use (Cone of Cold) it's suppose to slow the target/targets for 85% for 5 sec but it doesn't.

**Steps to reproduce the problem**:

1.  add the slow effect.

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=37265/cone-of-cold

**Comment by Athissa** [comment]
fixed
