### ISSUE TITLE
Cow

### ISSUE THREAD

**Issue by nutaraxen** [Athissa/Tracker#397]
**Describe the issue you're having**:
Cow in mulgore is not saying Mooo
**Explain how you expect it work**:
Cow should say mooo
**Steps to reproduce the problem**:

1. Fix cow
2. Fix moo chat
3. Fix moo sound

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=71444/cow

**Comment by AGrygor** [comment]
Very funny.
