### ISSUE TITLE
Problem on Northrend raid or dungeons

### ISSUE THREAD

**Issue by faseczka** [Athissa/Tracker#421]
**Describe the issue you're having**:
ALL NORTHREND DUNGEON AND RAIDS
**Explain how you expect it work**:
its been nice if someone look at this 
**Steps to reproduce the problem**:

1. voa ulduar 10/25 achivment dont work but in ulduar razor scale its bugged and teleport on next quater its not working
2. TOGC 10/25 cant started 
3. on icc 10/25 doesnt worg gun ship battle

**Links to Wowhead, YouTube, etc**:

**Comment by faseczka** [comment]
im weiting for repair that xD

**Comment by Ygdrassill** [comment]
Please add each bug separately, I'm closing this one so you can do that
