### ISSUE TITLE
Perte d'Athissa points

### ISSUE THREAD

**Issue by Guldarts** [Athissa/Tracker#433]
Bonjours,

Vendredi 12 Mai 2017 suite a un crach ou redémarrage du serveur j'ai perdu 150 AthissaPoints.
J'étais sur mon personnage et je voulais le up niveau 100 la transaction était en cours et BOUM. Plus rien et j'ai remarquée immédiatement la perte des mes points j'ai donc envoyer a MP à Athissa mais depuis le 12/05/2017 il ne s'est rien passée..

Aidez moi à récupérer ces quelques points.

**Comment by AGrygor** [comment]
Cher joueur, le bugtracker est dédié aux rapports de bug et non pas la boutique. Donc je vous conseillerai d'envoyer un email vers: staff@athissa.com avec votre mail du compte + username, et d'expliquer les details de votre soucis. Je vous remmerci de votre patience. Je lock ce sujet!

Cordialement,

Grygor.
