### ISSUE TITLE
Quest problem - Proving pit

### ISSUE THREAD

**Issue by Bast1onCZ** [Athissa/Tracker#435]
Hi,

I fould a quest that doesn't work: Proving Pit

When I try to speak to Darkspear Jailor, there is no option that can start the fight.

In my opinion this is very important quest, because it's one of the first when you start playing as a troll.

**Comment by AGrygor** [comment]
Dear player, you are not respecting the "Issue Format". So I will have to close the 2 issues you have opened.

Sincerely yours,

Grygor.
