### ISSUE TITLE
Marksmanship Hunter / World bosses

### ISSUE THREAD

**Issue by WestwudMMHunter** [Athissa/Tracker#438]
**Describe the issue you're having**:
I noticed when doing world bosses, I barely do any damage to them, but I do "normal" amount of damage to everything else(including dungeon/raid bosses). As you can see in the pictures below, Rancid Maw has done most of the damage. And this is only my trinket passive effect which can tell you how little damage my other abilities do. Also the minimum damage done by my piercing shot is 43k and maximum is 262k which is really low. It does max damage if I cast it at 100 focus, which should do a minimum of 500k+ damage (non crit).

When I asked other members of the party how much damage the tooltip of their abilities do, it matched with the damage meter. I don't know if this is a problem with any other class/spec but it sure is for MM hunters.

**Explain how you expect it work**:
I should be doing the same amount of damage to world bosses as any other mob in the game.

**Steps to reproduce the problem**:
1. Fight a world boss
2. Look at the damage

**Links to Wowhead, YouTube, etc**:
![screenshot_6](https://cloud.githubusercontent.com/assets/28875935/26365768/dc0aa8be-3fe8-11e7-87a0-2950ab5cf419.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/28875935/26365769/dc0cfe66-3fe8-11e7-951b-b1487f7e9684.png)

**Comment by AGrygor** [comment]
World Bosses have obtained 10 in armor, so physical damage is reduced. So the decrease in dps is quite normal.

**Comment by WestwudMMHunter** [comment]
I know that the damage would be reduced, but not by that much, i'm doing like 1/5 of what I should be. Also my trinkets damage should not out dps literally every other ability. And as I said before, I asked some members of the raid, and their damage on the tooltips matched with the dps on the meter.

**Comment by Athissa** [comment]
fixed
