### ISSUE TITLE
Subtlety: Dagger in the Dark

### ISSUE THREAD

**Issue by Sozeone** [Athissa/Tracker#444]
**Describe the issue you're having**:
Dagger in the Dark doesnt work 
**Explain how you expect it work**:
http://www.wowhead.com/spell=198675/dagger-in-the-dark
**Steps to reproduce the problem**:

1. cast stealth
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=198675/dagger-in-the-dark

**Comment by Ygdrassill** [comment]
I'm closing this post because not enough info was given, how to replicate it? What part is broken? How should it work?
