### ISSUE TITLE
Subtlety: Veil of midnight 

### ISSUE THREAD

**Issue by Sozeone** [Athissa/Tracker#445]
**Describe the issue you're having**:
Veil of midnight is not working at all.
**Explain how you expect it work**:
http://www.wowhead.com/spell=198952/veil-of-midnight
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
Veil of midnight is not working at all.http://www.wowhead.com/spell=198952/veil-of-midnight

**Comment by Ygdrassill** [comment]
I'm closing this post because not enough info was given, how to replicate it? What part is broken? How should it work?
