### ISSUE TITLE
Subtlety: Cold Blood

### ISSUE THREAD

**Issue by Sozeone** [Athissa/Tracker#446]
**Describe the issue you're having**:
Cold Blood doesnt work
**Explain how you expect it work**:
http://www.wowhead.com/spell=213981/cold-blood
**Steps to reproduce the problem**:

1.
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=213981/cold-blood

**Comment by Ygdrassill** [comment]
I'm closing this post because not enough info was given, how to replicate it? What part is broken? How should it work?
