### ISSUE TITLE
Cut to the Chase

### ISSUE THREAD

**Issue by Sozeone** [Athissa/Tracker#447]
**Describe the issue you're having**:
Cut to the Chase doesnt work
**Explain how you expect it work**:
http://www.wowhead.com/spell=197020/cut-to-the-chase
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=197020/cut-to-the-chase

**Comment by Ygdrassill** [comment]
I'm closing this post because not enough info was given, how to replicate it? What part is broken? How should it work?
