### ISSUE TITLE
Subtlety: Smoke Bomb

### ISSUE THREAD

**Issue by Sozeone** [Athissa/Tracker#448]
**Describe the issue you're having**:
Smoke Bomb doesnt work
**Explain how you expect it work**:
http://www.wowhead.com/spell=76577/smoke-bomb
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=76577/smoke-bomb

**Comment by Ygdrassill** [comment]
I'm closing this post because not enough info was given, how to replicate it? What part is broken? How should it work?
