### ISSUE TITLE
[NPC] Dalaran - Sky Admiral Rogers

### ISSUE THREAD

**Issue by Turokn** [Athissa/Tracker#45]
**Issue**: The NPC "Sky Admiral Rogers" isn't showing for completing the quest "Stormheim"

**How it should work**: The Sky Admiral Rogers should be waiting for the player inside the Violet Citadel in Dalaran.

**Steps to reproduce the problem**:

1. Get the quest Stormheim from your Scouting Map
2. Travel to the Violet Citadel in Dalaran

Stormheim : http://www.wowhead.com/quest=39735/stormheim
Sky Admiral Rogers : http://www.wowhead.com/npc=96644/sky-admiral-rogers

**Comment by AGrygor** [comment]
Stormheim will be introduced soon enough, so even if you take the quest it won't complete.
