### ISSUE TITLE
Mining Copper

### ISSUE THREAD

**Issue by Hifarius** [Athissa/Tracker#458]
**Describe the issue you're having**:
I think copper veins dont loot as much as the others veins (tin,iron,etc...)

**Explain how you expect it work**:
For exemple, copper veins loot 4 copper ores max and no gems when others veins loot 7 ores max and gems.
Maybe this is a problem about the loot rates of the server. The copper veins are not affected with the loot rates changes. This is just a possibility.

Thanks a lot for your works guys !

**Comment by Ygdrassill** [comment]
It works corecty
