### ISSUE TITLE
honor talnet doesnt work

### ISSUE THREAD

**Issue by saeedelahe** [Athissa/Tracker#471]
**Describe the issue you're having**:
Rogue subtlety honor talent "Phantom Assassine" doesnt work
**Explain how you expect it work**:
when i use shadow dance or become stealth my Symbol Of Death should turn on auetomatically but it doesnt 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Ygdrassill** [comment]
Next time Next time please post how to reproduce the problem and a Wowhead link to the talent, I'm closing this post
