### ISSUE TITLE
Subtlety talents and honor talents

### ISSUE THREAD

**Issue by bewilder1** [Athissa/Tracker#474]
**Describe the issue you're having**:

Weapon master does not work.
Master of subtlety and nightstalker does not work in shadow dance.
Strike from the shadow does not work.
Honor among thieves, cold blood and shadow's caress does not work.

**Explain how you expect it work**:

Self explanatory in spells's wowhead links. And master of subtlety and nightstalker should works within shadow dance

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=193537/weaponmaster
http://www.wowhead.com/spell=31223/master-of-subtlety
http://www.wowhead.com/spell=14062/nightstalker
http://www.wowhead.com/spell=196951/strike-from-the-shadows
http://www.wowhead.com/spell=209427/shadows-caress
http://www.wowhead.com/spell=51699/honor-among-thieves
http://www.wowhead.com/spell=213983/cold-blood

**Comment by Ygdrassill** [comment]
Im closing this post. Pease reports each spell separately so the developers can work on each one of them, if you post each bug together in 1 post it will confuse the developers. Have a good game

**Comment by bewilder1** [comment]
Well I already did my part posting alot of bugs, separately or multiple in each posts. Guess what ? No fix in almost a month, no differences between posting multiple bugs or one bug in one post. Why should I waste my time making each post for each bugs when even one post - one bug didn't even get fixed ? Also instead of closing it, why don't you help separating them so the bugged spells/talents/honor talents can be "addressed" in future time. Oh yea right, none of my business.
