### ISSUE TITLE
Trait du Chaos 

### ISSUE THREAD

**Issue by Maddus-FR** [Athissa/Tracker#475]
**Describe the issue you're having**: À l'aide du sort "trait du chaos" et peut être autre buff, les démonistes arrivent à faire entre 500 et 700k de dégats juste avec ce sort en champs de bataille. 

Certain se permettent d'en abuser comme : " Loocker "

**Explain how you expect it work**:  ne devrait pas faire autant de dégats

**Steps to reproduce the problem**:

1.  tester le sort en bg avec et sans buffs 
2. 
3. 

**Sanction du joueur Loocker demandée pour Abus de Bug.

**Links to Wowhead, YouTube, etc**: http://fr.wowhead.com/spell=116858/trait-du-chaos

**Comment by Maddus-FR** [comment]
la plainte accompagnée de screenshot affichant les coups à 600k 700k 500k et 200k avec ce même sort, lançé par le même démoniste au sein d'un même bg sur la même cible à chaque fois...

**Comment by GeneralissimeDarklinks** [comment]
Cela dépend l'ilvl du demoniste.
Le passif. http://fr.wowhead.com/spell=197912

Te donne des stats en fonction de deux point: Ton ilvl (equipements et armes prodigieuse) et tes traits d'arme prodigieuse.

De plus le sort qui en plus inflige un coup critique automatique  vois son dps augmenté via le score de critique du demoniste et de la maîtrise de la spé destruction qui est http://fr.wowhead.com/spell=77220
Donc je pense que sa dois venir de la maîtrise plutôt que du sort

**Comment by Athissa** [comment]
Le trait du chaos est 100% fonctionnel
Le spell fait plus de dégâts en PVP que PVE

Officiel : https://www.youtube.com/watch?v=3-tf47cWzww
Temps : 2m19s
Dégâts : 625k
