### ISSUE TITLE
Mage:Water elemental buged

### ISSUE THREAD

**Issue by Starlords** [Athissa/Tracker#477]
**Describe the issue you're having**: The water elemental doesen't follow you or assists on fighting unless you command it, just like the bug in warlock's Imp

**Explain how you expect it work**:It should follow you and attack your targets automatic

**Steps to reproduce the problem**:

1. Summon water element, walk around and you'll see that he stands still
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Ygdrassill** [comment]
Please  give wowhead link .im closing this  post so you can make a new one

**Comment by VictorTyne** [comment]
Where would a wowhead link tell you that the water elemental is supposed to follow you and assist in fighting? That is generally understood to be a feature of pets.
