### ISSUE TITLE
Stormwind guards don't give any informations

### ISSUE THREAD

**Issue by Starlords** [Athissa/Tracker#478]
**Describe the issue you're having**:Stormwind guards don't give any informations

**Explain how you expect it work**:Stormwind guards should give informations

**Steps to reproduce the problem**:

1. Click on Stormwind guards and you'll see that the talk window is blank
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Ygdrassill** [comment]
Please make another  post  whit  wowhed  link ,its needed for developers
