### ISSUE TITLE
Mulgore mobs not engaging in combat.

### ISSUE THREAD

**Issue by Gowa-san** [Athissa/Tracker#48]
**Describe the issue you're having**:
Mobs in Mulgore do not engage you in combat when attacked and therefore regenerate hp very quickly and are hard/impossible to kill. Your auto attack turns off and debuffs wear off immidietly.

**Explain how you expect it work**:
Mobs should fight you back.

**Steps to reproduce the problem**:

1. Go to Mulgore/Create a Tauren.
2. Attack any mob (except the ones fightning Tauren NPCs).

**Links to Wowhead, YouTube, etc**:
https://youtu.be/v6NSJ3klcJI

**Comment by Athissa** [comment]
fixed
