### ISSUE TITLE
Chaman amélioration: Tempête écrasante

### ISSUE THREAD

**Issue by yannled** [Athissa/Tracker#484]
**Describe the issue you're having**:
Le passif niveau 90 Tempête écrasante" des talents, devrait améliorer le sort "Impacte foudroyant afin d’électrifier le sol et infliger des dégâts sur la durée, dégâts qu'il n'inflige pas.
**Explain how you expect it work**:
Le sort Impacte foudroyant devrait faire des dégâts sur la durée après activation du talent "Tempête écrasante".
**Steps to reproduce the problem**:

1.  Activer le talent de niveau 90 "Tempête écrasante".
2.  Lancer le sort Impacte foudroyant et remarquer qu'il ne fait pas de dégâts sur la durée.
3. 

**Links to Wowhead, YouTube, etc**:
http://fr.wowhead.com/spell=187874/impact-foudroyant
http://fr.wowhead.com/spell=192246/tempete-ecrasante

**Comment by A-Edina** [comment]
Bug Tracker Issues are required to be English.
