### ISSUE TITLE
Elemental Focus

### ISSUE THREAD

**Issue by AVyrax** [Athissa/Tracker#492]
**Describe the issue you're having**:
Spell procs, but never gives 10% incr damage.
**Explain how you expect it work**:
Should give 10% incr damage.
**Steps to reproduce the problem**:

1. Cast a spell
2. Gain the proc/buff
3. Cast another spell, no damage difference

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=16164/elemental-focus

**Comment by Athissa** [comment]
Fixed
