### ISSUE TITLE
Ignore Pain

### ISSUE THREAD

**Issue by AVyrax** [Athissa/Tracker#493]
**Describe the issue you're having**:
Ignore pain scaling is off, it scales between 20-60 rage, and this is the correct formula.
**Explain how you expect it work**:
Fight through the pain, ignoring 90% of the next up to [(18.6) * Attack power * (1 + Versatility)] damage you take from any sources, based on Rage spent.
**Steps to reproduce the problem**:

1. Play a warrior
2. Spam Ignore pain
3. Solo anything you want.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=190456/ignore-pain

**Comment by Kazakon** [comment]
The only problem with ignore pain its the stacks.and solo Anything you want its lie . the amount of absord its correct. The cooldown its correct. So if you want to fix something that its the stacks. So thanks from the report.
