### ISSUE TITLE
Damage of "Eviscerate" is changing 

### ISSUE THREAD

**Issue by saeedelahe** [Athissa/Tracker#498]
**Describe the issue you're having**:
Class:Rogue  talent:Subtlety / damage of "Eviscerate" is changing when im in bg and out of bg , in bg that damage become very low , out of bg 315k, in bg or arena 180k
**Explain how you expect it work**:
That should be same in both bg and out of bg
**Steps to reproduce the problem**:

1. Go into bg
2. Go arena 
3. Check difference between them ( bg , arena and out of it )

**Links to Wowhead, YouTube, etc**:

**Comment by bewilder1** [comment]
its because pvp template, your stat reduced to a fixed stat.

**Comment by saeedelahe** [comment]
Thats not going to be fixed , in last server ( valhalla ) i didnt have this problem

**Comment by Sozeone** [comment]
y, its because pvp temp
