### ISSUE TITLE
Subltety several honor talents and talents doesnt work

### ISSUE THREAD

**Issue by saeedelahe** [Athissa/Tracker#501]
**Describe the issue you're having**:
Honor talent Rogue subtlety "Thief's Bargain" doesnt work
**Explain how you expect it work**:
Damage should decreased by an additional 20# and cooldown of" Vanish" spell should reduce by 90 sec 
**Steps to reproduce the problem**:

1. Fill "Thief's Bargain" as honor talent 
2. Use "Vanish" spell and see cooldown
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Sozeone** [comment]
Close this thread.ot works. It's a pvp talent. It works only in pvp
