### ISSUE TITLE
Honor talnet doesnt work

### ISSUE THREAD

**Issue by saeedelahe** [Athissa/Tracker#505]
**Describe the issue you're having**:
"Phantom Assassin" doesnt work completely
**Explain how you expect it work**:
While in stealth or "Shadow Dance " active that Symbol Of Death should turn on automatically
**Steps to reproduce the problem**:

1. Fill Phantom Assassin as a honor talent 
2. Become stealth or active shadow dance then see if symbol of death on ( check buff of hero)
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Sozeone** [comment]
Stop duplicating
