### ISSUE TITLE
[Warlock] [Spell] [Talent] [Demonology] Improved Dreadstalkers

### ISSUE THREAD

**Issue by VictorTyne** [Athissa/Tracker#509]
**Describe the issue you're having**:
The Wild Imps summoned during Call Dreadstalkers do not ride the dreadstalkers.

**Explain how you expect it work**:
The Wild Imps summoned during Call Dreadstalkers should ride the dreadstalkers.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Ygdrassill** [comment]
Please add better description and Wowhead link, I'm closing this issue, so you can make a new one
