### ISSUE TITLE
[NPC] Highmountain - Mayla Highmountain

### ISSUE THREAD

**Issue by Turokn** [Athissa/Tracker#51]
**Issue**: The NPC "[Mayla Highmountain](http://www.wowhead.com/npc=93826/mayla-highmountain)" doesn't give the quest "[A Walk With the Spirits](http://www.wowhead.com/quest=40515/a-walk-with-the-spirits)" nor "[The Skyhorn Tribe](http://www.wowhead.com/quest=38913/the-skyhorn-tribe)"

**How it should work**: [Mayla Highmountain](http://www.wowhead.com/npc=93826/mayla-highmountain) should give to the players who have completed : 
[The Introductory questline to Highmountain](http://www.wowhead.com/quest=39733/the-lone-mountain), [the Moozy Waterwise's Quest line](http://www.wowhead.com/quest=39323/moozys-sojourn), [The Jale Rivermane and Rivermane Shaman questline](http://www.wowhead.com/quest=39277/spray-and-prey) and [the Spiritwalker Ebonhorn and Warbrave Oro's questlines](http://www.wowhead.com/quest=39025/grasp-of-the-underking) the quests "[A Walk With the Spirits](http://www.wowhead.com/quest=40515/a-walk-with-the-spirits)" and "[The Skyhorn Tribe](http://www.wowhead.com/quest=38913/the-skyhorn-tribe)"

**Steps to reproduce the problem**:

1. Complete the questlines
2. Talk to [Mayla Highmountain](http://www.wowhead.com/npc=93826/mayla-highmountain)

**Comment by AGrygor** [comment]
Only 3 chapters are available for the moment, till the zone gets additional ones. Closing this Issue. Good Game.
