### ISSUE TITLE
Uldum Dungeons (Cataclysm)

### ISSUE THREAD

**Issue by reinhold11** [Athissa/Tracker#519]
Uldum Instances (Cataclysm)

0. Halls of Origination: (least important)

- You can kill almost every boss and get the Dungeon achievements

- except Anarphet: http://www.wowhead.com/npc=39788/anraphet

- the NPC in front of the door does not open the door as it should like in the following video:

- https://www.youtube.com/watch?v=B8L-bxi7jr8 at 5:50

1. Lost City of the Tol' Vir:

- everything is working except the last boss 

- reason: you can't use the whirlwind to get up to the platform, but you can hover over the invisible whirlwind and your mouse icon changes to the "mount on" icon, but it doesn't work. 

- but the boss is already waiting, so it spawned perfectly fine

- http://www.wowhead.com/lost-city-of-the-tolvir

- https://www.youtube.com/watch?v=femG9_6AkM8 at 8:55 for the whirlwind function

2. The Vortex Pinnacle:

- you can get to the first boss and kill him 

- you can't travel to the next platform as there is no whirlwind similar to the Lost City

- https://www.youtube.com/watch?v=4svHdiJvtOA&t=301s at 4:50

3. Throne of the Four Winds:

- bosses have spawned, but..

- you can't reach them as the wind travel mechanic does not work

- https://www.youtube.com/watch?v=PcN6gJvXwoc at 0:18

**Comment by Ygdrassill** [comment]
Please add each bug separately, I'm closing this issue, so you can do it
