### ISSUE TITLE
quest bug Paradise Lost.

### ISSUE THREAD

**Issue by pekacmarko** [Athissa/Tracker#529]
**Describe the issue you're having**: When I took the quest of class hall to go to Azsuna. When I wanted to finish the quest to Khadgar missing at Krasus' Landing in Dalaran.

**Explain how you expect it work**: Khadgar must be at Krasus' Landing in Dalaran and to get quest Down to Azsuna.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/quest=39718/paradise-lost

**Comment by Ygdrassill** [comment]
At the moment only highmounten quest work

**Comment by Athissa** [comment]
fixed
