### ISSUE TITLE
[World quest] Mixology Mix-up 

### ISSUE THREAD

**Issue by Molinu** [Athissa/Tracker#530]
**Describe the issue you're having**:
There are two area in this world quest but the server only considers one
So we can't farm [Intact Murloc eye](http://www.wowhead.com/item=136838)
[Pic](https://image.noelshack.com/fichiers/2017/22/1496146056-wowscrnshot-053017-1324612.jpg)

**Explain how you expect it work**:
We should be able to access the zone to farm [Intact Murloc eye](http://www.wowhead.com/item=136838)

**Steps to reproduce the problem**:

1. Go Azsuna, /way 51 32 (TomTom Add-ons)
2. Walk towards the murlocs

**Links to Wowhead, YouTube, etc**:
[Mixology Mix-up](http://www.wowhead.com/quest=42105/mixology-mix-up)
[Mixology Mix-up Video](http://www.wowhead.com/quest=42105/mixology-mix-up#videos:id=107442)

**Comment by Athissa** [comment]
fixed
