### ISSUE TITLE
[Hellfire Peninsula] The Dark Portal doesn't allow travel back to Azeroth

### ISSUE THREAD

**Issue by VictorTyne** [Athissa/Tracker#545]
**Describe the issue you're having**:
The Dark Portal doesn't allow travel back to Azeroth

**Explain how you expect it work**:
The Dark Portal should allow travel back to Azeroth

**Steps to reproduce the problem**:

1. go to portal in hellfire
2.
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by AVyrax** [comment]
There are two portals, one for horde, one for alliance. They're on the left/right respectively. One goes to ORG other goes to SW.
