### ISSUE TITLE
World quests not working

### ISSUE THREAD

**Issue by splitsecond93** [Athissa/Tracker#547]
**Describe the issue you're having**:
World quests appear on map, but when i get to the spot, they seem not to be there
**Explain how you expect it work**:
They should pop up when you get to the area of world quest like they did in the first place, than they just stopped
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Ygdrassill** [comment]
Please add a  Wowhead link, I'm closing this issue so you can remake it
