### ISSUE TITLE
Quest Listing aszuna

### ISSUE THREAD

**Issue by GeneralissimeDarklinks** [Athissa/Tracker#548]
The canvas will not be respected for this point but I do not count spammer the bugtracker for an area so do in one I am sorry

Demon souls
http://www.wowhead.com/quest=37653/

The crystal pop well but kill the demons ready of them does not count 

http://www.wowhead.com/quest=37660/

The crystals are present and function but no demons appears and impossible to speak to Allari

**Comment by GeneralissimeDarklinks** [comment]
The crystals are present and function but no demons appears and impossible to speak to Allar

**Comment by AGrygor** [comment]
Even if the canvas wasn't respected, it should be one issue subject per quest. Yours Sincerely.

Grygor.

**Comment by Athissa** [comment]
fixed
