### ISSUE TITLE
Devine hammer not generating holy power

### ISSUE THREAD

**Issue by fadida14** [Athissa/Tracker#551]
**Describe the issue you're having**:
Title ^
**Explain how you expect it work**:
devine hammer's description says that it generates 2 holy power
**Steps to reproduce the problem**:

1. go into paladin account 
2. use devine hammer  
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Ygdrassill** [comment]
Please add a description on the issue and Wowhead link, I'm closing this issue so you can remake it
