### ISSUE TITLE
[Quest] Challiane Vineyards

### ISSUE THREAD

**Issue by Astrizel** [Athissa/Tracker#552]
**Describe the issue you're having**:
the last quest item, the "nightrose recipe: part 3 instructions doesn't drop from the intended npc
**Explain how you expect it work**:
it should be a 100% drop like the other 2 items required for the quest
**Steps to reproduce the problem**:

1. get quest from npc in challiance's terrace
2. kill npcs for nightrose recipe: parts 1 and 2 instructions
3. kill the last npc for nightrose recipe: part 3 instructions

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=38203/challiane-vineyards

**Comment by Athissa** [comment]
fixed
