### ISSUE TITLE
Blade of Wrath not working 

### ISSUE THREAD

**Issue by fadida14** [Athissa/Tracker#557]
**Describe the issue you're having**:
Title ^
**Explain how you expect it work**:
Blade of wrath should reset the cooldown of Blade of justice 
**Steps to reproduce the problem**:

1. go into paladin account 
2. use Blade of justice so it goes on cooldown 
3. spam all other abilitys 

**Links to Wowhead, YouTube, etc**:

**Comment by Ygdrassill** [comment]
Please add a description on the issue and Wowhead link, I'm closing this issue so you can remake it
