### ISSUE TITLE
[Quest] For the Corn!

### ISSUE THREAD

**Issue by Astrizel** [Athissa/Tracker#558]
**Describe the issue you're having**:
you can't loot the barrel for the quest items
**Explain how you expect it work**:
the barrels should be clickable for the player to loot the quest items 
**Steps to reproduce the problem**:

1. get quest from npc
2. go to the indicated zone in minimap
3. try looting the barrel for the quest item

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=38647/for-the-corn

**Comment by Athissa** [comment]
Fixed
