### ISSUE TITLE
[Quest] The Consumed

### ISSUE THREAD

**Issue by Astrizel** [Athissa/Tracker#559]
**Describe the issue you're having**:
you can't loot the DIm Ley Crystal for the item needed to revive the whelpling
**Explain how you expect it work**:
the crystal should be lootable for the needed item
**Steps to reproduce the problem**:

1. take quest from npc
2. go to a dim ley crystal
3. try to loot it

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=37859/the-consumed

**Comment by Athissa** [comment]
fixed
