### ISSUE TITLE
DK Sindragosa's Fury

### ISSUE THREAD

**Issue by wearpon95** [Athissa/Tracker#563]
**Describe the issue you're having**:

the spell doesn't work at all  no animation no dammage just the sound

**Explain how you expect it work**:
the spell should do that
https://www.youtube.com/watch?v=fzDaZtAs1pc
https://www.youtube.com/watch?v=mHFBKziG0zo

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.askmrrobot.com/wow/theory/mechanic/spell/sindragosasfury?spec=DeathKnightFrost&version=live

**Comment by AGrygor** [comment]
#242  Already reported here.
