### ISSUE TITLE
DK Crystalline Swords

### ISSUE THREAD

**Issue by wearpon95** [Athissa/Tracker#564]
**Describe the issue you're having**:

the passif proc to often 

**Explain how you expect it work**:

the pourcentage of the passif should be 45 %
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

http://www.askmrrobot.com/wow/theory/mechanic/spell/crystallineswords?spec=DeathKnightFrost&version=live

**Comment by AGrygor** [comment]
#494  Already reported.
