### ISSUE TITLE
Sindragosa's Fury

### ISSUE THREAD

**Issue by wearpon95** [Athissa/Tracker#565]
**Describe the issue you're having**:

The spell do no animation , no dommage , just the sound

**Explain how you expect it work**:

https://www.youtube.com/watch?v=mHFBKziG0zo
  
that should work like the video show

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by AGrygor** [comment]
Dear player, I have already answered about this spell. Please refrain from rewriting these subjects. Thank you.
