### ISSUE TITLE
[Legion][quest] Morale booster

### ISSUE THREAD

**Issue by Lzeir** [Athissa/Tracker#567]
**Describe the issue you're having**: Ooka dooker does not give fighter chow

**Explain how you expect it work**: talking to ooka dooker gives fighter chow and quest credit 

**Steps to reproduce the problem**:

1. take quest
2. ...
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/quest=37536/morale-booster

**Comment by Athissa** [comment]
fixed
