### ISSUE TITLE
[Borean Tundra] [Quest] [Horde] Bury those Cockroaches!

### ISSUE THREAD

**Issue by VictorTyne** [Athissa/Tracker#579]
**Describe the issue you're having**:
Bury those Cockroaches! is broken. You cannot plant the charge at the sinkholes to complete the quest.

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Ygdrassill** [comment]
I'm closing this post, not enough information given, and no Wowhead link
