### ISSUE TITLE
[Blade's Edge Mountains] [Quest] The Stones of Vekh'nir

### ISSUE THREAD

**Issue by VictorTyne** [Athissa/Tracker#582]
**Describe the issue you're having**:
The Stones of Vekh'nir quest cannot be completed. After charging the crystal in the spell circle you are not awarded quest credit and thus cannot turn it in.

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Ygdrassill** [comment]
Please add better explanation, and wowhead link. I'm closing this issue, so you can do it.
