### ISSUE TITLE
[Feral][Talents] - Blood Talons

### ISSUE THREAD

**Issue by Treetard** [Athissa/Tracker#600]
[Blood Talons](http://www.wowhead.com/spell=155672/bloodtalons) should proc on using regrowth, it does not.
 However, it does proc on Healing Touch, which you require Resto affinity for to be able to use it.
Even though, this still renders this amazing talent obsolete, since Healing Touch is only usable in humanoid form.

**Comment by Ygdrassill** [comment]
Not enough information, no Wowhead link, I will need to close this issue, so you can remake it, in the correct way.
