### ISSUE TITLE
[Feral][Traits] - Ashamane's Bite

### ISSUE THREAD

**Issue by Treetard** [Athissa/Tracker#624]
[Ashamane's Bite](http://www.wowhead.com/spell=210702/ashamanes-bite) doesn't work.

**Comment by Ygdrassill** [comment]
Not enough information, no Wowhead link, I will need to close this issue, so you can remake it, in the correct way.

**Comment by Treetard** [comment]
All the information you need is right there.
The link is right there.
Good luck in reporting issues, I will not do it any longer.
