### ISSUE TITLE
[Feral][Traits] - Scent of Blood

### ISSUE THREAD

**Issue by Treetard** [Athissa/Tracker#625]
[Scent of Blood](http://www.wowhead.com/spell=196838/scent-of-blood) doesn't work.

**Comment by Ygdrassill** [comment]
Not enough information, no Wowhead link, I will need to close this issue, so you can remake it, in the correct way.

**Comment by Treetard** [comment]
All the information you need is right there.
The link is right there.
I will never spend any more second on this waste of time, some gratitude.
