### ISSUE TITLE
Pnj Bug avec les quetes de draenor

### ISSUE THREAD

**Issue by Mika83160** [Athissa/Tracker#76]
**Describe the issue you're having**:
Probleme de Pnj draenor 
**Explain how you expect it work**:
Que la quette du donjon marche
**Steps to reproduce the problem**:

1. Prendre la quete.
2. ce faire auto valide la quette par 1 Mj "Noxias".
3. rendre la quette et ne pas pouvoir prendre les armes dans le Pnj.

**Links to Wowhead, YouTube, etc**:http://fr.wowhead.com/npc=88155/maitresse-des-defis-savina , http://fr.wowhead.com/quest=37279/un-defi-de-taille-le-seigneur-de-guerre-zaela

**Comment by Maddus-FR** [comment]
> Explain how you expect it work:
Que la quette du donjon marche

En l’occurrence : " Cette quête est marquée comme obsolète par Blizzard et ne peut être obtenue ou accomplie. " comme précisé sur wowhead, elle doit être donc supprimée.
