### ISSUE TITLE
[Paladin] Talent - Blinding Light

### ISSUE THREAD

**Issue by Astrizel** [Athissa/Tracker#77]
**Describe the issue you're having**:
spell doesn't do damage or crowd-controls them but does the animation
**Explain how you expect it work**:
spell should do damage and crowd-control the target/s
**Steps to reproduce the problem**:

1. target a mob
2. get aggro from mob
3. use spell, check for crowd-control debuff and damage

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=115750

**Comment by Athissa** [comment]
fixed
